EntityClass: ProductListPriceHistory
EntityNamespace: 'Platy.AdventureWorks.Repository.Data.Entities'
EntityBaseClass: DomainEntity
TableNaming: Singular
ContextProperty: ProductListPriceHistories
TableSchema: 'Production'
TableName: 'ProductListPriceHistory'
MappingClass: ProductListPriceHistoryConfiguration
MappingNamespace: 'Platy.AdventureWorks.Repository.Data.EntityConfiguration'
MapperClass: ProductListPriceHistoryProfile
MapperNamespace: 'ProductListPriceHistoryProfile'
MapperBaseClass: Profile
IsView: False
Properties:
  - PropertyName: ProductId
    ColumnName: 'ProductID'
    StoreType: @int
    NativeType: '@int'
    DataType: Int32
    SystemType: Int32
    IsNullable: False
    IsPrimaryKey: True
    IsForeignKey: True
    IsRowVersion: False
    IsUnique: False
  - PropertyName: StartDate
    ColumnName: 'StartDate'
    StoreType: datetime
    NativeType: 'datetime'
    DataType: DateTime
    SystemType: DateTime
    IsNullable: False
    IsPrimaryKey: True
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: EndDate
    ColumnName: 'EndDate'
    StoreType: datetime
    NativeType: 'datetime'
    DataType: DateTime
    SystemType: DateTime
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: ListPrice
    ColumnName: 'ListPrice'
    StoreType: money
    NativeType: 'money'
    DataType: Currency
    SystemType: Decimal
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: ModifiedDate
    ColumnName: 'ModifiedDate'
    StoreType: datetime
    NativeType: 'datetime'
    DataType: DateTime
    SystemType: DateTime
    Default: '(getdate())'
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
