EntityClass: ProductSubcategory
EntityNamespace: 'Platy.AdventureWorks.Repository.Data.Entities'
EntityBaseClass: DomainEntity
TableNaming: Singular
ContextProperty: ProductSubcategories
TableSchema: 'Production'
TableName: 'ProductSubcategory'
MappingClass: ProductSubcategoryMap
MappingNamespace: 'Platy.AdventureWorks.Repository.Data.EntityConfiguration'
MapperClass: ProductSubcategoryProfile
MapperNamespace: 'ProductSubcategoryProfile'
MapperBaseClass: Profile
IsView: False
Properties:
    - PropertyName: ProductSubcategoryID
      ColumnName: 'ProductSubcategoryID'
      StoreType: @int
      NativeType: '@int'
      DataType: Int32
      SystemType: Int32
      ValueGenerated: OnAdd
      IsNullable: False
      IsPrimaryKey: True
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: ProductCategoryID
      ColumnName: 'ProductCategoryID'
      StoreType: @int
      NativeType: '@int'
      DataType: Int32
      SystemType: Int32
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: True
      IsRowVersion: False
      IsUnique: False
    - PropertyName: Name
      ColumnName: 'Name'
      StoreType: nvarchar(50)
      NativeType: 'nvarchar'
      DataType: String
      SystemType: String
      Size: 50
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: True
    - PropertyName: Rowguid
      ColumnName: 'rowguid'
      StoreType: uniqueidentifier
      NativeType: 'uniqueidentifier'
      DataType: Guid
      SystemType: Guid
      Default: '(newid())'
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: True
    - PropertyName: ModifiedDate
      ColumnName: 'ModifiedDate'
      StoreType: datetime
      NativeType: 'datetime'
      DataType: DateTime
      SystemType: DateTime
      Default: '(getdate())'
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
