EntityClass: ProductDescription
EntityNamespace: 'Platy.AdventureWorks.Repository.Data.Entities'
EntityBaseClass: DomainEntity
TableNaming: Singular
ContextProperty: ProductDescriptions
TableSchema: 'Production'
TableName: 'ProductDescription'
MappingClass: ProductDescriptionMap
MappingNamespace: 'Platy.AdventureWorks.Repository.Data.EntityConfiguration'
MapperClass: ProductDescriptionProfile
MapperNamespace: 'ProductDescriptionProfile'
MapperBaseClass: Profile
IsView: False
Properties:
    - PropertyName: ProductDescriptionID
      ColumnName: 'ProductDescriptionID'
      StoreType: @int
      NativeType: '@int'
      DataType: Int32
      SystemType: Int32
      ValueGenerated: OnAdd
      IsNullable: False
      IsPrimaryKey: True
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: Description
      ColumnName: 'Description'
      StoreType: nvarchar(400)
      NativeType: 'nvarchar'
      DataType: String
      SystemType: String
      Size: 400
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: Rowguid
      ColumnName: 'rowguid'
      StoreType: uniqueidentifier
      NativeType: 'uniqueidentifier'
      DataType: Guid
      SystemType: Guid
      Default: '(newid())'
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: True
    - PropertyName: ModifiedDate
      ColumnName: 'ModifiedDate'
      StoreType: datetime
      NativeType: 'datetime'
      DataType: DateTime
      SystemType: DateTime
      Default: '(getdate())'
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
