EntityClass: Product
EntityNamespace: 'Platy.AdventureWorks.Repository.Data.Entities'
EntityBaseClass: DomainEntity
TableNaming: Singular
ContextProperty: Products
TableSchema: 'Production'
TableName: 'Product'
MappingClass: ProductConfiguration
MappingNamespace: 'Platy.AdventureWorks.Repository.Data.EntityConfiguration'
MapperClass: ProductProfile
MapperNamespace: 'ProductProfile'
MapperBaseClass: Profile
IsView: False
Properties:
  - PropertyName: Id
    ColumnName: 'ProductID'
    StoreType: @int
    NativeType: '@int'
    DataType: Int32
    SystemType: Int32
    ValueGenerated: OnAdd
    IsNullable: False
    IsPrimaryKey: True
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: Name
    ColumnName: 'Name'
    StoreType: nvarchar(50)
    NativeType: 'nvarchar'
    DataType: String
    SystemType: String
    Size: 50
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: True
  - PropertyName: ProductNumber
    ColumnName: 'ProductNumber'
    StoreType: nvarchar(25)
    NativeType: 'nvarchar'
    DataType: String
    SystemType: String
    Size: 25
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: True
  - PropertyName: MakeFlag
    ColumnName: 'MakeFlag'
    StoreType: bit
    NativeType: 'bit'
    DataType: Boolean
    SystemType: Boolean
    Default: '((1))'
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: FinishedGoodsFlag
    ColumnName: 'FinishedGoodsFlag'
    StoreType: bit
    NativeType: 'bit'
    DataType: Boolean
    SystemType: Boolean
    Default: '((1))'
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: Color
    ColumnName: 'Color'
    StoreType: nvarchar(15)
    NativeType: 'nvarchar'
    DataType: String
    SystemType: String
    Size: 15
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: SafetyStockLevel
    ColumnName: 'SafetyStockLevel'
    StoreType: smallint
    NativeType: 'smallint'
    DataType: Int16
    SystemType: Int16
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: ReorderPoint
    ColumnName: 'ReorderPoint'
    StoreType: smallint
    NativeType: 'smallint'
    DataType: Int16
    SystemType: Int16
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: StandardCost
    ColumnName: 'StandardCost'
    StoreType: money
    NativeType: 'money'
    DataType: Currency
    SystemType: Decimal
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: ListPrice
    ColumnName: 'ListPrice'
    StoreType: money
    NativeType: 'money'
    DataType: Currency
    SystemType: Decimal
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: Size
    ColumnName: 'Size'
    StoreType: nvarchar(5)
    NativeType: 'nvarchar'
    DataType: String
    SystemType: String
    Size: 5
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: SizeUnitMeasureCode
    ColumnName: 'SizeUnitMeasureCode'
    StoreType: nchar(3)
    NativeType: 'nchar'
    DataType: StringFixedLength
    SystemType: String
    Size: 3
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: True
    IsRowVersion: False
    IsUnique: False
  - PropertyName: WeightUnitMeasureCode
    ColumnName: 'WeightUnitMeasureCode'
    StoreType: nchar(3)
    NativeType: 'nchar'
    DataType: StringFixedLength
    SystemType: String
    Size: 3
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: True
    IsRowVersion: False
    IsUnique: False
  - PropertyName: Weight
    ColumnName: 'Weight'
    StoreType: decimal(8,2)
    NativeType: '@decimal'
    DataType: Decimal
    SystemType: Decimal
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: DaysToManufacture
    ColumnName: 'DaysToManufacture'
    StoreType: @int
    NativeType: '@int'
    DataType: Int32
    SystemType: Int32
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: ProductLine
    ColumnName: 'ProductLine'
    StoreType: nchar(2)
    NativeType: 'nchar'
    DataType: StringFixedLength
    SystemType: String
    Size: 2
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: Class
    ColumnName: 'Class'
    StoreType: nchar(2)
    NativeType: 'nchar'
    DataType: StringFixedLength
    SystemType: String
    Size: 2
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: Style
    ColumnName: 'Style'
    StoreType: nchar(2)
    NativeType: 'nchar'
    DataType: StringFixedLength
    SystemType: String
    Size: 2
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: ProductSubcategoryId
    ColumnName: 'ProductSubcategoryID'
    StoreType: @int
    NativeType: '@int'
    DataType: Int32
    SystemType: Int32
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: True
    IsRowVersion: False
    IsUnique: False
  - PropertyName: ProductModelId
    ColumnName: 'ProductModelID'
    StoreType: @int
    NativeType: '@int'
    DataType: Int32
    SystemType: Int32
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: True
    IsRowVersion: False
    IsUnique: False
  - PropertyName: SellStartDate
    ColumnName: 'SellStartDate'
    StoreType: datetime
    NativeType: 'datetime'
    DataType: DateTime
    SystemType: DateTime
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: SellEndDate
    ColumnName: 'SellEndDate'
    StoreType: datetime
    NativeType: 'datetime'
    DataType: DateTime
    SystemType: DateTime
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: DiscontinuedDate
    ColumnName: 'DiscontinuedDate'
    StoreType: datetime
    NativeType: 'datetime'
    DataType: DateTime
    SystemType: DateTime
    IsNullable: True
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
  - PropertyName: Rowguid
    ColumnName: 'rowguid'
    StoreType: uniqueidentifier
    NativeType: 'uniqueidentifier'
    DataType: Guid
    SystemType: Guid
    Default: '(newid())'
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: True
  - PropertyName: ModifiedDate
    ColumnName: 'ModifiedDate'
    StoreType: datetime
    NativeType: 'datetime'
    DataType: DateTime
    SystemType: DateTime
    Default: '(getdate())'
    IsNullable: False
    IsPrimaryKey: False
    IsForeignKey: False
    IsRowVersion: False
    IsUnique: False
