EntityClass: ProductReview
EntityNamespace: 'Platy.AdventureWorks.Repository.Data.Entities'
EntityBaseClass: DomainEntity
TableNaming: Singular
ContextProperty: ProductReviews
TableSchema: 'Production'
TableName: 'ProductReview'
MappingClass: ProductReviewMap
MappingNamespace: 'Platy.AdventureWorks.Repository.Data.EntityConfiguration'
MapperClass: ProductReviewProfile
MapperNamespace: 'ProductReviewProfile'
MapperBaseClass: Profile
IsView: False
Properties:
    - PropertyName: ProductReviewID
      ColumnName: 'ProductReviewID'
      StoreType: @int
      NativeType: '@int'
      DataType: Int32
      SystemType: Int32
      ValueGenerated: OnAdd
      IsNullable: False
      IsPrimaryKey: True
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: ProductID
      ColumnName: 'ProductID'
      StoreType: @int
      NativeType: '@int'
      DataType: Int32
      SystemType: Int32
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: True
      IsRowVersion: False
      IsUnique: False
    - PropertyName: ReviewerName
      ColumnName: 'ReviewerName'
      StoreType: nvarchar(50)
      NativeType: 'nvarchar'
      DataType: String
      SystemType: String
      Size: 50
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: ReviewDate
      ColumnName: 'ReviewDate'
      StoreType: datetime
      NativeType: 'datetime'
      DataType: DateTime
      SystemType: DateTime
      Default: '(getdate())'
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: EmailAddress
      ColumnName: 'EmailAddress'
      StoreType: nvarchar(50)
      NativeType: 'nvarchar'
      DataType: String
      SystemType: String
      Size: 50
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: Rating
      ColumnName: 'Rating'
      StoreType: @int
      NativeType: '@int'
      DataType: Int32
      SystemType: Int32
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: Comments
      ColumnName: 'Comments'
      StoreType: nvarchar(3850)
      NativeType: 'nvarchar'
      DataType: String
      SystemType: String
      Size: 3850
      IsNullable: True
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: ModifiedDate
      ColumnName: 'ModifiedDate'
      StoreType: datetime
      NativeType: 'datetime'
      DataType: DateTime
      SystemType: DateTime
      Default: '(getdate())'
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
