EntityClass: ProductPhoto
EntityNamespace: 'Platy.AdventureWorks.Repository.Data.Entities'
EntityBaseClass: DomainEntity
TableNaming: Singular
ContextProperty: ProductPhotos
TableSchema: 'Production'
TableName: 'ProductPhoto'
MappingClass: ProductPhotoMap
MappingNamespace: 'Platy.AdventureWorks.Repository.Data.EntityConfiguration'
MapperClass: ProductPhotoProfile
MapperNamespace: 'ProductPhotoProfile'
MapperBaseClass: Profile
IsView: False
Properties:
    - PropertyName: ProductPhotoID
      ColumnName: 'ProductPhotoID'
      StoreType: @int
      NativeType: '@int'
      DataType: Int32
      SystemType: Int32
      ValueGenerated: OnAdd
      IsNullable: False
      IsPrimaryKey: True
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: ThumbNailPhoto
      ColumnName: 'ThumbNailPhoto'
      StoreType: varbinary(max)
      NativeType: 'varbinary'
      DataType: Binary
      SystemType: Byte[]
      Size: -1
      IsNullable: True
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: ThumbnailPhotoFileName
      ColumnName: 'ThumbnailPhotoFileName'
      StoreType: nvarchar(50)
      NativeType: 'nvarchar'
      DataType: String
      SystemType: String
      Size: 50
      IsNullable: True
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: LargePhoto
      ColumnName: 'LargePhoto'
      StoreType: varbinary(max)
      NativeType: 'varbinary'
      DataType: Binary
      SystemType: Byte[]
      Size: -1
      IsNullable: True
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: LargePhotoFileName
      ColumnName: 'LargePhotoFileName'
      StoreType: nvarchar(50)
      NativeType: 'nvarchar'
      DataType: String
      SystemType: String
      Size: 50
      IsNullable: True
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
    - PropertyName: ModifiedDate
      ColumnName: 'ModifiedDate'
      StoreType: datetime
      NativeType: 'datetime'
      DataType: DateTime
      SystemType: DateTime
      Default: '(getdate())'
      IsNullable: False
      IsPrimaryKey: False
      IsForeignKey: False
      IsRowVersion: False
      IsUnique: False
